### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nk932714** [MrManchot/blockinstagram#2]
Fatal error: Class 'Module' not found in/blockinstagram-master/blockinstagram.php on line 4

**Comment by MrManchot** [comment]
Your module directory should be "blockinstagram" not "blockinstagram-master"

**Comment by nk932714** [comment]
i corrected that now a new error is dispalying 

**Parse error: syntax error, unexpected '(', expecting '{' in /home/public_html/insta/blockinstagram/blockinstagram.php on line 3**

**Comment by nk932714** [comment]
If i change the syntax in line 3 from '()' to '{}' then this error displaying 

**Parse error: syntax error, unexpected 'const' (T_CONST) in /home/public_html/insta/blockinstagram/blockinstagram.php on line 6**

**Comment by MrManchot** [comment]
The module required at least PHP 5.3 ;)

**Comment by nk932714** [comment]
my PHP Version 5.5.35      :(

**Comment by nk932714** [comment]
should i downgrade to 5.3

**Comment by MrManchot** [comment]
Sorry it was not the PHP version

The directory must be : /home/public_html/insta/modules/blockinstagram/

**Comment by nk932714** [comment]
If You have time then can you please tell me the steps to use this repo may be i am doing something wrong. :(

1 ) when using this as 
![image](https://user-images.githubusercontent.com/29853208/31123100-1dbe7f02-a85c-11e7-8a7a-99b434d7ee49.png)

error :- 
![image](https://user-images.githubusercontent.com/29853208/31123122-345177f6-a85c-11e7-9801-117ab92b0eec.png)


2) when ( changed to { 
![image](https://user-images.githubusercontent.com/29853208/31123158-581eb7d4-a85c-11e7-9d25-1bc00a10cf2e.png)




error :-
![image](https://user-images.githubusercontent.com/29853208/31123022-ddf3a14a-a85b-11e7-8f99-7470663bcc5b.png)


PHP Version:

![image](https://user-images.githubusercontent.com/29853208/31122995-bc0bc36e-a85b-11e7-88c8-4fb574cb8d25.png)

**Comment by LittleSnake42** [comment]
![image](https://user-images.githubusercontent.com/24939197/31124112-48cd37ba-a843-11e7-9b56-6664ca8a11a6.png)

Actually the code in the repository is this. You should not modify the module code.

**Comment by nk932714** [comment]
ok i will freshly upload everything 

**Edit**

now the code is same as in repo nothing is modified 
![image](https://user-images.githubusercontent.com/29853208/31158890-a773eb52-a8e2-11e7-8ad7-ebde78191f8f.png)
but still it is dispalying the error :( 

![image](https://user-images.githubusercontent.com/29853208/31158914-c81f8ea6-a8e2-11e7-980c-e69d54e54c08.png)
