### ISSUE TITLE
Doesn't work as ?__a=1 is blocked

### ISSUE THREAD

**Issue by mwyr** [MrManchot/blockinstagram#4]

**Comment by koyhl** [comment]
I solved the problem,
This is my repair file on MrManchot's free modules
[blockinstagram.zip](https://github.com/MrManchot/blockinstagram/files/1928608/blockinstagram.zip)

**Comment by William-Kara** [comment]
Thanks for the fix.

**Comment by koyhl** [comment]
No problem,
This will continue to be fixed from FB but I will try to figure out how to fix them.

**Comment by MrManchot** [comment]
Hello @koyhl 

Nice job, If you wanna, you can do a Pull Request, I will accept it, and make the 1.2.3 release :)

**Comment by koyhl** [comment]
I do not know what to ask for.

**Comment by MrManchot** [comment]
I integrate your modification, here the new release : https://github.com/MrManchot/blockinstagram/releases/tag/1.2.3

**Comment by koyhl** [comment]
Yes, Thanks you so much.

**Comment by mwyr** [comment]
Great job, thank you! :)
